apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdm-dashboard
  labels:
    app: rdm-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdm-dashboard
  template:
    metadata:
      labels:
        app: rdm-dashboard
    spec:
      containers:
        - name: rdm-dashboard
          image: ghcr.io/tugraz-rdm/rdm:devel
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rdm-dashboard-app
spec:
  selector:
    app: rdm-dashboard
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rdm-dashboard-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: rdm.k3s.cyverse.at
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rdm-dashboard-app
                port:
                  number: 3000
